package com.udacity.data;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBQueryExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBScanExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.PaginatedQueryList;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;

import org.apache.log4j.Logger;

@DynamoDBTable(tableName = "PLACEHOLDER_COURSES_TABLE_NAME")
public class Course {

    // get the table name from env. var. set in serverless.yml
    private static final String COURSES_TABLE_NAME = System.getenv("COURSES_TABLE_NAME");

    private static DynamoDBAdapter db_adapter;
    private final AmazonDynamoDB client;
    private final DynamoDBMapper mapper;

    private Logger logger = Logger.getLogger(this.getClass());

    private String id;
    private String name;
    private Float ratings;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBRangeKey(attributeName = "name")
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "ratings")
    public Float getRatings() {
        return this.ratings;
    }
    public void setRatings(Float ratings) {
        this.ratings = ratings;
    }

    public Course() {
        // build the mapper config
        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
            .withTableNameOverride(new DynamoDBMapperConfig.TableNameOverride(COURSES_TABLE_NAME))
            .build();
        // get the db adapter
        this.db_adapter = DynamoDBAdapter.getInstance();
        this.client = this.db_adapter.getDbClient();
        // create the mapper with config
        this.mapper = this.db_adapter.createDbMapper(mapperConfig);
    }

    public String toString() {
        return String.format("Course [id=%s, name=%s, ratings=$%f]", this.id, this.name, this.ratings);
    }

    // methods
    public Boolean ifTableExists() {
        return this.client.describeTable(COURSES_TABLE_NAME).getTable().getTableStatus().equals("ACTIVE");
    }

    public List<Course> list() throws IOException {
      DynamoDBScanExpression scanExp = new DynamoDBScanExpression();
      List<Course> results = this.mapper.scan(Course.class, scanExp);
      for (Course p : results) {
        logger.info("Courses - list(): " + p.toString());
      }
      return results;
    }

    public Course get(String id) throws IOException {
        Course course = null;

        HashMap<String, AttributeValue> av = new HashMap<String, AttributeValue>();
        av.put(":v1", new AttributeValue().withS(id));

        DynamoDBQueryExpression<Course> queryExp = new DynamoDBQueryExpression<Course>()
            .withKeyConditionExpression("id = :v1")
            .withExpressionAttributeValues(av);

        PaginatedQueryList<Course> result = this.mapper.query(Course.class, queryExp);
        if (result.size() > 0) {
          course = result.get(0);
          logger.info("Courses - get(): course - " + course.toString());
        } else {
          logger.info("Courses - get(): course - Not Found.");
        }
        return course;
    }

    public void save(Course course) throws IOException {
        logger.info("Courses - save(): " + course.toString());
        this.mapper.save(course);
    }

    public Boolean delete(String id) throws IOException {
        Course course = null;

        // get course if exists
        course = get(id);
        if (course != null) {
          logger.info("Courses - delete(): " + course.toString());
          this.mapper.delete(course);
        } else {
          logger.info("Courses - delete(): course - does not exist.");
          return false;
        }
        return true;
    }

}
