package com.udacity.data;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBQueryExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBScanExpression;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.PaginatedQueryList;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;

import org.apache.log4j.Logger;

@DynamoDBTable(tableName = "PLACEHOLDER_TODO_TABLE_NAME")
public class ToDo {

    // get the table name from env. var. set in serverless.yml
    private static final String TODO_TABLE_NAME = System.getenv("TODO_TABLE_NAME");

    private static DynamoDBAdapter db_adapter;
    private final AmazonDynamoDB client;
    private final DynamoDBMapper mapper;

    private Logger logger = Logger.getLogger(this.getClass());

    private String id;
    private String name;
    private String dueDate;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBRangeKey(attributeName = "name")
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "dueDate")
    public String getDueDate() {
        return this.dueDate;
    }
    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    public ToDo() {
        // build the mapper config
        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
            .withTableNameOverride(new DynamoDBMapperConfig.TableNameOverride(TODO_TABLE_NAME))
            .build();
        // get the db adapter
        this.db_adapter = DynamoDBAdapter.getInstance();
        this.client = this.db_adapter.getDbClient();
        // create the mapper with config
        this.mapper = this.db_adapter.createDbMapper(mapperConfig);
    }

    public String toString() {
        return String.format("To Do [id=%s, name=%s, dueDate=%s]", this.id, this.name, this.dueDate);
    }

    // methods
    public Boolean ifTableExists() {
        return this.client.describeTable(TODO_TABLE_NAME).getTable().getTableStatus().equals("ACTIVE");
    }

    public List<ToDo> list() throws IOException {
      DynamoDBScanExpression scanExp = new DynamoDBScanExpression();
      List<ToDo> results = this.mapper.scan(ToDo.class, scanExp);
      for (ToDo p : results) {
        logger.info("To Dos - list(): " + p.toString());
      }
      return results;
    }

    public ToDo get(String id) throws IOException {
        ToDo toDo = null;

        HashMap<String, AttributeValue> av = new HashMap<String, AttributeValue>();
        av.put(":v1", new AttributeValue().withS(id));

        DynamoDBQueryExpression<ToDo> queryExp = new DynamoDBQueryExpression<ToDo>()
            .withKeyConditionExpression("id = :v1")
            .withExpressionAttributeValues(av);

        PaginatedQueryList<ToDo> result = this.mapper.query(ToDo.class, queryExp);
        if (result.size() > 0) {
          toDo = result.get(0);
          logger.info("To Dos - get(): To Do - " + toDo.toString());
        } else {
          logger.info("To Dos - get(): To Do - Not Found.");
        }
        return toDo;
    }

    public void save(ToDo toDo) throws IOException {
        logger.info("To Dos - save(): " + toDo.toString());
        this.mapper.save(toDo);
    }

    public Boolean delete(String id) throws IOException {
        ToDo toDo = null;

        // get ToDo if exists
        toDo = get(id);
        if (toDo != null) {
          logger.info("To Dos - delete(): " + toDo.toString());
          this.mapper.delete(toDo);
        } else {
          logger.info("To Dos - delete(): To Do - does not exist.");
          return false;
        }
        return true;
    }

}
